"""campos para book añadidos

Revision ID: 12304311270a
Revises: 559fb67f376d
Create Date: 2025-12-05 15:44:00.429328

"""
from typing import Sequence, Union

import advanced_alchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '12304311270a'
down_revision: Union[str, Sequence[str], None] = '559fb67f376d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.add_column('books', sa.Column('language', sa.String(), nullable=False))
    op.add_column('books', sa.Column('publisher', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'language')
    op.drop_column('books', 'description')
    op.drop_column('books', 'stock')
    # ### end Alembic commands ###
