"""Loan status y due date

Revision ID: 71f1f07df5a6
Revises: 7be0b1c17855
Create Date: 2025-12-05 17:39:25.280044

"""
from typing import Sequence, Union

import advanced_alchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '71f1f07df5a6'
down_revision: Union[str, Sequence[str], None] = '7be0b1c17855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

loan_status_enum = sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='loanstatus')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    loan_status_enum.create(op.get_bind(), checkfirst=False)
    op.add_column('loans', sa.Column('due_date', sa.Date(), server_default=sa.text("'2025-01-01'"), nullable=False))
    op.add_column('loans', sa.Column('fine_amount', sa.Numeric(), nullable=True))
    op.add_column('loans', sa.Column('status', loan_status_enum, server_default=sa.text("'ACTIVE'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'status')
    op.drop_column('loans', 'fine_amount')
    op.drop_column('loans', 'due_date')
    loan_status_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
